### ISSUE TITLE
Fix city pipeline

### ISSUE THREAD

**Issue by LeDuySon** [YoungIT/godeye-core#26]
City pipeline is currently having errors. Please fix it + add unit test

**Comment by CaoHoangTung** [comment]
if country_name not in Country:
                group_key = "Unknown"
            else:
                group_key = Country[country_name].value.name
            country_group[group_key].append(city.value)

**Comment by CaoHoangTung** [comment]
https://github.com/YoungIT/godeye-core/pull/35
